server:
  port: 80

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8760/eureka


# 公共配置
spring:
  datasource:
    name: 主库
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/backend?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: Chen1436863821.
  redis:
    host: 127.0.0.1
    port: 6379
    password: Chen1436863821.
  #  mvc:
  #    throw-exception-if-no-handler-found: true
  #  resources:
  #    add-mappings: false
  jackson:
    default-property-inclusion: non_null
