spring:
  profiles:
    active: @env@
  application:
    name: @project.artifactId@
  main:
    allow-bean-definition-overriding: true
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: app-config
#      name: common,manage
#      fail-fast: true
#      profile: @env@
